spring: 
    datasource:
        # mysql
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://52.116.40.222:3306/empresa_seguro
        username: root
        password: uX8bD5%ypdBaibm
    jpa:
        hibernate:
            ddl-auto: create

        #oracle
        # driver-class-name: oracle.jdbc.OracleDriver
        # url: jdbc:oracle:thin:@169.47.92.94:1521/OracleDriver/ORCL
        # username: system
        # password: csmIBM2022SSA